parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: '8889'
    database_name: jobeet_test
    database_user: smmbx
    database_password: mbx123456
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 507352ee9b798d514b793a20a9aae4ec359b16de
    database_path: null
